### ISSUE TITLE
Dynamic path

### ISSUE THREAD

**Issue by benoj** [lineupninja/ninjafire#3]
Hey, 

This seems like a cool project. I already have a database in place however. I'm just wondering how I would model my current data in this. At present I have data which looks something like this (hopefullly my diagram makes sense!):
```

/organisations/{orgId}/ 
     { name: "My Organisation" }
/jobs/{orgId}/
     {job1Id}/
         { 
             name :  "job1", 
              applicants: { candidateId1: true}  
           }
     {job2Id}/
         { 
                name :  "job2" ,  
              applicants: { candidateId2: true}
          }
/candidates/{orgId}/
     {candidateId1}/
         { 
                name :  "Candidate1",  
                 jobs: { jobId1} 
           }
     {candidateId2}/
         { 
              name :  "job2" , 
             jobs: { jobId2}
          }
```

Basically most of my data is organised under an *orgId* how would i set the base path for each model to be like this?

**Comment by elgordino** [comment]
Hi. Apologies for not addressing this. This project is now archived as we have migrated away from Firebase.
